// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZp5xHAmGdGn2JJl-2vQkzc1k1_sdCDU4',
    appId: '1:6034816826:web:9ea2a9c863306fad761a03',
    messagingSenderId: '6034816826',
    projectId: 'quick-sz',
    authDomain: 'quick-sz.firebaseapp.com',
    storageBucket: 'quick-sz.appspot.com',
    measurementId: 'G-DRYZ220SMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDglnCxGDlXLiL6Dz_uUtbkiF9EypNH7Rg',
    appId: '1:6034816826:android:aff5437d1f1fd42d761a03',
    messagingSenderId: '6034816826',
    projectId: 'quick-sz',
    storageBucket: 'quick-sz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiFqm4ca1u-EOOyMG1PthANslFdZuCl38',
    appId: '1:6034816826:ios:32427bf7be181d57761a03',
    messagingSenderId: '6034816826',
    projectId: 'quick-sz',
    storageBucket: 'quick-sz.appspot.com',
    iosClientId: '6034816826-8ph93h7mnqhcujt1hse3f0n07r696aid.apps.googleusercontent.com',
    iosBundleId: 'in.sinnoor.quick',
  );
}
